---
apiVersion: v2
name: netbird
description: NetBird VPN management platform
type: application
version: 1.5.4-rc14 # TODO: update before merging
appVersion: "0.32.0" # TODO: update before merging
icon: https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/kuu5tm1wt09ztp6ctlag
