{{- if .Values.management.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - port: {{ .Values.management.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "netbird.management.selectorLabels" . | nindent 4 }}
{{- end }}
