apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ include "netbird.namespace" . }} 
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ include "netbird.namespace" . }} 
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "netbird.management.serviceAccountName" . }}
  namespace: {{ include "netbird.namespace" . }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "netbird.fullname" . }}-management
