apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird.fullname" . }}-management
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
data:
  management.tmpl.json: |-
    {{- .Values.configuration |nindent 4 }}
  kubeconfig-gen.sh: |-
    #!/bin/bash

    # Set variables
    TOKEN_PATH="/run/secrets/kubernetes.io/serviceaccount/token"
    CA_CERT_PATH="/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    NAMESPACE_PATH="/run/secrets/kubernetes.io/serviceaccount/namespace"

    API_SERVER="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"

    # Read values
    TOKEN=$(cat ${TOKEN_PATH})
    NAMESPACE=$(cat ${NAMESPACE_PATH})

    # Create kubeconfig
    KUBECONFIG_PATH="/tmp/kubeconfig"
    cat <<EOF > ${KUBECONFIG_PATH}
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: ${CA_CERT_PATH}
        server: ${API_SERVER}
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        namespace: ${NAMESPACE}
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        token: ${TOKEN}
    EOF
