{{- if .Values.signal.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbird.fullname" . }}-signal
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.signal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.signal.replicaCount }}
  selector:
    matchLabels:
      {{- include "netbird.signal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.signal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netbird.signal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.signal.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbird.signal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.signal.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-signal
          securityContext:
            {{- toYaml .Values.signal.securityContext | nindent 12 }}
          image: "{{ .Values.signal.image.repository }}:{{ .Values.signal.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.signal.image.pullPolicy }}
          args:
            - "--port"
            - "{{ .Values.signal.service.port }}"
            - "--log-level"
            - "{{ .Values.signal.logLevel }}"
            - "--log-file"
            - "console"
          ports:
            - name: {{ .Values.signal.service.name }}
              containerPort: {{ .Values.signal.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.signal.service.name }}
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.signal.service.name }}
          resources:
            {{- toYaml .Values.signal.resources | nindent 12 }}
      {{- with .Values.signal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.signal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.signal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
