apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-signal
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "netbird.signal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.signal.service.type }}
  ports:
    - port: {{ .Values.signal.service.port }}
      targetPort: {{ .Values.signal.service.name }}
      protocol: TCP
      name: {{ .Values.signal.service.name }}
  selector:
    {{- include "netbird.signal.selectorLabels" . | nindent 4 }}
